theme: jekyll-theme-midnight
#remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed

title: FtD Blueprint Bot for Discord
email: fefafi@netcologne.de
description: >-
  Discord bot for "From the Depths" which creates images from .blueprint files.
baseurl: "fruchtba3r.github.io/FtD-Blueprint-Bot/"
url: "https://fruchtba3r.github.io/FtD-Blueprint-Bot/"
github_username: FRUCHTBA3R

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/