remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed

title: FtD Blueprint Bot for Discord
email: fefafi@netcologne.de
description: >-
  Discord bot for "From the Depths" which creates images from .blueprint files.
baseurl: ""
url: ""
github_username: FRUCHTBA3R
